---
#
# setup the livestream supervisor settings
#

- name: create hive-client directory
  file: path=hive-client state=directory mode=0755

- name: Copy The local hive client
  unarchive: src=hive-client.zip dest={{ hive_client_path }}

- name: Copy the config for this client
  template: src=config.py dest={{ hive_client_path }}/config.py

- name: setup virtualenv
  pip: requirements={{ hive_client_path }}/requirements.txt virtualenv={{ hive_client_path }}/.venv

- name: Cron for sensors
  cron: name="sensor-temp-humidity" minute="*/5" job="cd {{ hive_client_path }};sudo .venv/bin/python manage.py temperature_humidity"
  sudo: no

- name: Run register
  shell: cd {{ hive_client_path }};sudo .venv/bin/python manage.py register

- name: Run first sensor event
  shell: cd {{ hive_client_path }};sudo .venv/bin/python manage.py temperature_humidity
