---
# ansible-playbook -c paramiko -i hosts setup.yml --ask-pass --sudo
- hosts: all
  sudo: yes
  user: pi

  tasks:
    - name: Creates destination directory on the Pi for our key.
      authorized_key: user=pi key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

