---
- hosts: all
  remote_user: pi
  sudo: no
  gather_facts: yes

  roles:
     # - common
     # - futurice.supervisor
     # - nginx
     # - raspberry_livestream
     - hive_client

  # tasks:
  #   - name: Final greeting upon successful Completion.
  #     pause: prompt="If you've got this far without any errors everything is probably okay! Press [Enter] to continue."
  #   - name: rebooting
  #     sudo: yes
  #     action: command /sbin/reboot -t now
