---
#
# setup the livestream supervisor settings
#

- name: Copy our supervisor settings
  synchronize: src=stream.supervisor.conf dest=/etc/supervisor/conf.d/stream.supervisor.conf
  sudo: yes

- name: Create rasberry_livestream dir in /home/pi/rasberry_livestream
  file: path={{ livestream_path }} state=directory

- name: Copy the stream.sh executable
  template: src=stream.sh dest={{ livestream_path }}/stream.sh

- name: Restart supervisorctl
  shell: supervisorctl restart raspberry_livestream
  sudo: yes

- name: Restart nginx
  action: service name=nginx state=restarted
  sudo: yes